### ISSUE TITLE
...

### ISSUE THREAD

**Issue by divisionbyzeroerror** [ome/omero-server-docker#24]
...

**Comment by manics** [comment]
We'll looking into it for the next major release of OMERO: https://trello.com/c/WRIsPbje/143-support-tls-1

In the short term you can make a [manual change to the server](https://github.com/openmicroscopy/openmicroscopy/blob/v5.4.10/etc/templates/grid/templates.xml#L475-L478), but you'd also need to update the clients too. In the case of Java this means recompiling them:
- https://github.com/openmicroscopy/openmicroscopy/blob/v5.4.10/components/tools/OmeroPy/src/omero/clients.py#L211
- https://github.com/openmicroscopy/openmicroscopy/blob/v5.4.10/components/blitz/src/omero/client.java#L353

**Comment by manics** [comment]
Note port 4063 is unencrypted, the scan showing TLSv1.2 is incorrect.

**Comment by funqtion** [comment]
@manics is TLS on port 4063 optional? Seems odd to me that it would respond to an SSL handshake if it was completely unavailable.

**Comment by joshmoore** [comment]
4063(tcp) is open by default but optional, both in the sense that you can tell OMERO to not open it and that clients can survive with access only to 4064(ssl) via the padlock icon.

**Comment by mtbc** [comment]
> via the padlock icon

In that regard also note [[trello] Default to secure-only OMERO tcp connections](https://trello.com/c/2g8oY2Ah/568-default-to-secure-only-omero-tcp-connections).

**Comment by manics** [comment]
Closing, original reporter has deleted the text of the issue
