### ISSUE TITLE
Link to example from README

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-server-docker#28]
Any objections to pointing this README as well as omero-web-docker to https://github.com/ome/docker-example-omero to side-step the regular issues with orchestration?

cc: @manics

**Comment by manics** [comment]
Sounds sensible

**Comment by joshmoore** [comment]
see:
 * https://github.com/ome/omero-server-docker/pull/29
 * https://github.com/ome/omero-web-docker/pull/32
