### ISSUE TITLE
LDAP with Users with Multiple Accounts with Identical Common Names

### ISSUE THREAD

**Issue by simonkidd** [ome/omero-server-docker#43]
Hi Omero team

Our AD structure has users with multiple logins that use identical CNs for FirstName/LastName. When these people login LDAP returns the exception below (edited for GDPR purposes),

`Default choice on create user: John Doe JDoe (ome.conditions.ApiUsageException: Cannot find unique user DistinguishedName: found=2 (John Doe)`

Is there a way we can define the Username as the account UID rather than FirstName/LastName or something else?

Our Omero configuration is as below.
`omero.ldap.user.filter=(objectClass=person)`
`omero.ldap.user.mapping=omeName=uid,firstName=givenName,lastName=sn,email=mail`

Kind regards,
Simon

**Comment by joshmoore** [comment]
The key for the second property is `omero.ldap.user_mapping`.

See also https://forum.image.sc/t/omero-ldap-issues/41255

**Comment by simonkidd** [comment]
Thanks Josh.
That link is to a query my colleague wrote which I applied early this morning, adding the double underscore in the Docker container 'recipe' worked a treat!

-e CONFIG_omero_ldap_user**__**mapping=omeName=uid,firstName=givenName,lastName=sn,email=mail \
-e CONFIG_omero_ldap_user**__**filter='(objectClass=Person)' \

Thanks!
Simon
