### ISSUE TITLE
Help with GA tests for ansible roles

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-server-docker#79]
Dear All,

As we are trying to offshore some maintenance work, we were wondering if anyone would be available to pitch in on PRs for updating the GA tests for ansible roles used in this repo to work also on following platforms:
- Rocky Linux 9
- Ubuntu 22.04

The list of ansible repositories used in the requirements.yml file of this repo is

[ansible-role-basedeps](https://github.com/ome/ansible-role-basedeps)
[ansible-role-ice](https://github.com/ome/ansible-role-ice)
[ansible-role-java](https://github.com/ome/ansible-role-java)
[ansible-role-omero-common](https://github.com/ome/ansible-role-omero-common)
[ansible-role-omero-server](https://github.com/ome/ansible-role-omero-server)
[ansible-role-postresql-client](https://github.com/ome/ansible-role-postgresql-client)

@JonnyJD, @dpwrussell, @bbladesGH, @stephenogg, @drjrkuhn, @JulianHn, @MicheleBortol, @glyg, @markovendelin, @lucalianas, @jackyko1991, @erickmartins, @Tom-TBT, @PaulVanSchayck, @sukunis, @aherbert

**Comment by jburel** [comment]
List of PRs currently WIP or approved
- https://github.com/ome/ansible-role-postgresql-client/pull/8
- https://github.com/ome/ansible-role-java/pull/14
- https://github.com/ome/ansible-role-omero-common/pull/8
- https://github.com/ome/ansible-role-omero-web/pull/47
- https://github.com/ome/ansible-role-omero-server/pulls

**Comment by jburel** [comment]
Using https://github.com/ome/ansible-role-omero-server/pull/69 and the various PRs (with adjustments) we now have OMERO.server running on a RHEL 9 VM

**Comment by jburel** [comment]
Work completed
